---
# Install OS specfic dependencies and OS specific rsp sessions tarball
- include_tasks: setup-RedHat7.yml
  when:
   - ansible_os_family == 'RedHat'
   - ansible_distribution_major_version == '7'

# - include_tasks: setup-RedHat8.yml
#   when:
#    - ansible_os_family == 'RedHat'
#    - ansible_distribution_major_version == '8'

- include_tasks: setup-Ubuntu16.yml
  when:
   - ansible_distribution == 'Ubuntu'
   - ansible_distribution_major_version == '16'

- include_tasks: setup-Ubuntu18.yml
  when:
   - ansible_distribution == 'Ubuntu'
   - ansible_distribution_major_version == '18'
