---
- name: install rsp dependencies
  apt:
   name:
    - curl
    - libcurl4-gnutls-dev
    - libssl1.0.0
    - libssl-dev
    - libuser
    - libuser1-dev
    - rrdtool
   update_cache: yes

# Create rstudio service account group
- name: create rstudio-server group
  group:
   name: "{{ rsp_rstudio_group }}"
   gid: "{{ rsp_rstudio_gid }}"
   state: present

# Create rstudio service account user
- name: create rstudio-server user
  user:
   name: "{{ rsp_rstudio_user }}"
   uid: "{{ rsp_rstudio_uid }}"
   groups: "{{ rsp_rstudio_group }}"
   state: present
   append: true

# Fetch rsp components
- name: download rsp session components
  get_url:
   url: "{{ rsp_url }}/xenial/rsp-session-xenial-{{ rsp_version }}.tar.gz"
   dest: /tmp/rsp-session-xenial-{{ rsp_version }}.tar.gz

# Check if existing rsp-session-component exists and get version
- name: check for existing rsp-session binaries and version
  command: |
   cat /usr/lib/rstudio-server/VERSION
  register: rsp_current_version
  failed_when: false
  changed_when: false

# Setup rstudio-server directory
- name: create /usr/lib/rstudio-server directory
  file:
   dest: /usr/lib/rstudio-server
   state: directory
   owner: root
   group: root
   mode: 0655
  when: rsp_current_version == ''

# Ensure rsp-session tmp directory exists
- name: ensure rsp-session tmp directory exists
  file:
   path: /tmp/rsp-session-xenial-{{ rsp_version }}
   state: directory

# Copy over tarball contents
- name: extract file contents of tarball
  unarchive:
   src: /tmp/rsp-session-xenial-{{ rsp_version }}.tar.gz
   dest: /tmp/rsp-session-xenial-{{ rsp_version }}
   remote_src: true
  when: rsp_current_version != rsp_version

# copy extracted content into rsp binary location
- name: copy extracted files to rsp binaries directory
  copy:
   src: /tmp/rsp-session-xenial-{{ rsp_version }}/rsp-session-xenial-{{ rsp_version }}/
   dest: /usr/lib/rstudio-server
   remote_src: true
  when: rsp_current_version != rsp_version
